import Card from '@/components/cards/primary/Card';
import Sidebar from '@/components/sidebar/primary/Sidebar';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CCG Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar title="Components" arrayOfLinks={['Cards', 'Nav', 'Sidebar']} />
      {/* <Sidebar title="Layouts" arrayOfLinks={['Header', 'Footer', 'Nav']} /> */}
      <main className={styles.main}>
        <h2 className={styles.title}>CCG Components</h2>
        <div className={styles.grid}>
          <Card
            tag="Tag"
            title="Title"
            body="Body"
            author="Author"
            time="Time"
            imgURL="/default-img.png"
            avatarURL="/default-img.png"
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
